baseURL = "https://example.com"
title = "HUBbit"
author = "Jay Leizl Reyes"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = ""

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']
  googleFonts = true

  [params.logo]
    main = "img/logo/hubbitlogo.png"
    alt = "HUBbit Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "HUBbit Trading & IT Services"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true
    
  [params.homepage_meta_tags]
    meta_description = "A Hugo App for HUBbit project"
    meta_og_title = "HUBbit"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "facebook"
    url = "https://www.facebook.com/hubbittrading/"
    pre = "<i class='fab fa-facebook-square'></i>"
      weight = 2

homepage = "https://github.com/opera7133/tella"
demosite = "https://tella.pages.dev"

tags = ["light", "simple", "blog", "clean", "tailwindcss", "responsive", "company", "modern", "slide"]
features = ["blog", "slides", "responsive"]

